apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: rmxq4da1o-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/rmxq4da1o-java-quarkus-gitops